name: "Segregation of Duties (SOD) Buddy"
description: "Ensures segregation of duties by enforcing approval rules based on the APPROVER files."
author:
inputs:
  token:
    description: "GitHub token"
    required: true
  repo:
    description: "Repository name"
    required: true
  owner:
    description: "Repository owner"
    required: true
  pull_number:
    description: "Pull request number"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "shield"
  color: "blue"
