name: 'SODBuddy'
description: 'Enforces segregation of duties by checking CODEOWNERS file.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: 'blue'
